title: Dennis Imanuel # your name (or website title) here
logo: "/images/asik.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
   <br><br>
   Undergraduate Mathematics student with data analytics professional working experience and an aspiring data scientist.
   <br><br>
   
   ## Contact Me

   If you have any questions or would like to discuss potential opportunities, please feel free to reach out to me:

   - Email: [dennisirwanto101@gmail.com]
   <a href="https://www.linkedin.com/in/dennis-imanuel-irwanto-547600236/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
